import * as React from "react";
import { Tooltip, withStyles, Theme } from "@material-ui/core";

export let HtmlTooltip = withStyles((theme: Theme) => ({
  tooltip: {
    backgroundColor: "transparent",
    maxWidth: 420,
    position: "relative",
  },
  tooltipPlacementTop: {
    "& .arrow": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "10px 7.5px 0 7.5px",
      borderColor: "#ffffff transparent transparent transparent",
      position: "absolute",
      top: "calc(100% - 1px)",
      left: "50%",
      transform: "translateX(-50%)",
      zIndex: 1,
    },
    "& .arrow-underlay": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "12px 8px 0 8px",
      borderColor: "currentColor transparent transparent transparent",
      position: "absolute",
      top: "calc(100% - 1px)",
      left: "50%",
      transform: "translateX(-50%)",
      zIndex: 0,
    },
  },
  tooltipPlacementRight: {
    "& .arrow": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "7.5px 10px 7.5px 0",
      borderColor: "transparent white transparent transparent",
      position: "absolute",
      top: "50%",
      right: "calc(100% - 1px)",
      transform: "translateY(-50%)",
      zIndex: 1,
    },
    "& .arrow-underlay": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "8px 12px 8px 0",
      borderColor: "transparent currentColor transparent transparent",
      position: "absolute",
      top: "50%",
      right: "calc(100% - 1px)",
      transform: "translateY(-50%)",
      zIndex: 0,
    },
  },
  tooltipPlacementBottom: {
    "& .arrow": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "0 7.5px 10px 7.5px",
      borderColor: " transparent transparent #ffffff transparent",
      position: "absolute",
      bottom: "calc(100% - 1px)",
      left: "50%",
      transform: "translateX(-50%)",
      zIndex: 1,
    },
    "& .arrow-underlay": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "0 8px 12px 8px",
      borderColor: " transparent transparent currentColor transparent",
      position: "absolute",
      bottom: "calc(100% - 1px)",
      left: "50%",
      transform: "translateX(-50%)",
      zIndex: 0,
    },
  },
  tooltipPlacementLeft: {
    "& .arrow": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "7.5px 0 7.5px 10px",
      borderColor: "transparent transparent transparent #ffffff",
      position: "absolute",
      top: "50%",
      left: "calc(100% - 1px)",
      transform: "translateY(-50%)",
      zIndex: 1,
    },
    "& .arrow-underlay": {
      width: 0,
      height: 0,
      borderStyle: "solid",
      borderWidth: "8px 0 8px 12px",
      borderColor: "transparent transparent transparent currentColor",
      position: "absolute",
      top: "50%",
      left: "calc(100% - 1px)",
      transform: "translateY(-50%)",
      zIndex: 0,
    },
  },
}))(Tooltip);
